### ISSUE TITLE
Use configuration providers

### ISSUE THREAD

**Issue by TheTedder** [MaxwellGordonC/ThreadFriendBot#11]
Currently, the app uses Microsoft's JSON library to read from a config file directly. This works, but it would be nice to make use of .NET's [Configuration Providers](https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration) for a more flexible and extensible approach.

**Comment by MaxwellGordonC** [comment]
I will address this in a future version when I address configurability.

**Comment by MaxwellGordonC** [comment]
Solved with the previous merge.
